global:
  resolve_timeout: 5m

# Шаблоны для Telegram
templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 5s      # Уменьшено с 10s до 5s
  group_interval: 5s  # Уменьшено с 10s до 5s
  repeat_interval: 1h # Уменьшено с 12h до 1h
  receiver: 'telegram'
  routes:
    - match:
        severity: critical
      receiver: 'telegram-critical'
      group_wait: 0s      # Критические алерты отправляются сразу
      group_interval: 5s
      continue: true
    - match:
        severity: warning
      receiver: 'telegram-warning'
      group_wait: 5s
      group_interval: 5s
      continue: true

receivers:
  - name: 'telegram'
    webhook_configs:
      - url: 'http://telegram-webhook:8080/telegram'
        send_resolved: true

  - name: 'telegram-critical'
    webhook_configs:
      - url: 'http://telegram-webhook:8080/telegram'
        send_resolved: true

  - name: 'telegram-warning'
    webhook_configs:
      - url: 'http://telegram-webhook:8080/telegram'
        send_resolved: true
