all:
  children:
    consul_servers:
      hosts:
        consul-server-1:
          ansible_host: 51.250.1.88
          consul_node_name: consul-server-1
        consul-server-2:
          ansible_host: 51.250.95.217
          consul_node_name: consul-server-2
        consul-server-3:
          ansible_host: 46.21.246.91
          consul_node_name: consul-server-3
      vars:
        consul_mode: server
        consul_bootstrap_expect: 3

    consul_clients:
      hosts:
        consul-client-1:
          ansible_host: 62.84.114.1
          consul_node_name: consul-client-1
      vars:
        consul_mode: client

    web_servers:
      hosts:
        web-1:
          ansible_host: 51.250.7.12
          ansible_host_private: 10.20.0.3
        web-2:
          ansible_host: 84.201.129.218
          ansible_host_private: 10.20.0.38
        web-3:
          ansible_host: 89.169.129.29
          ansible_host_private: 10.20.0.29

    opensearch_servers:
      hosts:
        opensearch-1:
          ansible_host: 62.84.117.35
          ansible_host_private: 10.20.0.28

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/sedunovsv/.ssh/id_ed25519
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    consul_version: 1.19.0
    consul_bind_ip: "{{ ansible_default_ipv4.address }}"
    consul_datacenter: dc1
    consul_domain: consul
    consul_log_level: INFO
