apiVersion: v1
kind: Secret
metadata:
  name: backup-s3
  namespace: kube-system
type: Opaque
stringData:
  access_key: "SET_ME"
  secret_key: "SET_ME"
  region: "ru-central1"
  bucket: "your-bucket-name"

